version: "3.7"

services:
  caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: callmetak/caddy-cloudflare-dns:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webserver

    environment:
      CLOUDFLARE_API_TOKEN: REDACTED
      CLOUDFLARE_EMAIL: REDACTED
volumes:
  caddy_data:
    external: true
  caddy_config:
    name: caddy_config

networks:
  webserver:
    name: webserver
    external: true

